---
title: "Clustering Resolution"
author: "Karsten Bach"
date: '`r Sys.Date()`'
output:
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: united
    highlight: tango
    code_folding: hide
---
***

```{r, message=FALSE,warning=FALSE}
library(scran)
library(scater)
library(plyr)
library(dplyr)
library(knitr)
library(ggplot2)
library(cowplot)
library(Matrix)
library(irlba)
theme_set(theme_cowplot())

sce <- readRDS("../data/Robjects/SCE_QC_norm.rds")

umap <- read.csv("../data/Robjects/UMAP_corrected.csv",stringsAsFactors=FALSE)[,-1]
clst <- read.csv("../data/Robjects/Clusters_w7.csv",stringsAsFactors=FALSE)[,-1]
anno <- left_join(umap,clst)
sce <- sce[,anno$barcode]
pD <- data.frame(colData(sce))
pD <- left_join(pD,anno[,c("barcode","UMAP1","UMAP2","Cluster")])
colData(sce) <- DataFrame(pD)
reducedDim(sce, type="UMAP") <- pD[,c("UMAP1","UMAP2")]
```


# Major Groups
```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
# Epithelial
plotUMAP(sce, colour_by="Epcam", text_by="Cluster") + ggtitle("Epithelial")
plotExpression(sce, x="Cluster", features=c("Epcam")) + ggtitle("Epithelial")
epithelial <- c(46,20,16,2,29,26,27,31,41,36,
		30,18,34,39,28,38,52) # 52 also has Ptprc
epiCluster <- paste0("C",epithelial)

# Immune
plotExpression(sce, x="Cluster", features=c("Ptprc")) + ggtitle("Immune")
plotUMAP(sce, colour_by="Ptprc", text_by="Cluster") + ggtitle("Immune")
immune <- c(32,9,24,50,51,10,4,19,
	    3,49,13,14,43,47,37,
	    48,
	    11, # Mast cells CPA3
	    22) # B-Cells Cd79a
	    
#	    52)
#neutros <- c(1) # not ptprc pos but S100a8
#plasma <- c(24) # not ptprc but Jchain
immuneCluster <- paste0("C",c(immune))

# Fibroblasts
plotUMAP(sce, colour_by="Col1a1", text_by="Cluster")
plotExpression(sce, x="Cluster", features="Col3a1") + ggtitle("Fibroblasts")
fibroblasts <- c(15,5,42,55,23,1,25,53,7,35)
#35 is different to all others
fibroblastsCluster <- paste0("C",fibroblasts)

mark <- findMarkers(sce,sce$Cluster,pval.type="all")
# mark.c40 <- data.frame(mark[["C40"]])
mark.c48 <- data.frame(mark[["C48"]])

# Stroma
# 8 is Schwann Cell (Mbp, Mpz)
# 34 lymphatic endothelium (Nts, # not really Lyve1 but Nts marked the lymphatic endothelium in prev)
# 2,31,34 are endothelium (Emcn)
# 7 Higd1b,Rgs5,Gm13889, Rgs4 no idea, will label as stroma
# C30 has weird expression of Ptprc and Epcam, doublets?

# Stroma
stroma <- c(33,54,6,# Endothelium # 54 is lymphatic
	    8, # Schwann 
	    40, # associates w Endothelium but not sure what it is also has Emcn
	    17,21, # not sure have Gm13889 and Il6
	    12, # not sure either maybe damaged?
	    45, # not sure
	    44) #could also be immune?

plotExpression(sce, x="Cluster", features=c("Mbp","Mpz")) + ggtitle("Schwann")
plotExpression(sce, x="Cluster", features=c("Emcn")) + ggtitle("Endothelium")
plotUMAP(sce, colour_by="Emcn", text_by="Cluster") + ggtitle("Endothelium")
plotExpression(sce, x="Cluster", features=c("Nts")) + ggtitle("LymphEndo")
stromaCluster <- paste0("C",stroma)

sce$MajorGroups <- mapvalues(as.character(sce$Cluster),
		       from=c(epiCluster, immuneCluster, fibroblastsCluster, stromaCluster),
		       to=c(rep("Epithelial",length(epiCluster)),
			    rep("Immune",length(immuneCluster)),
			    rep("Fibroblast",length(fibroblastsCluster)),
			    rep("Stroma",length(stromaCluster))))
# Finer Annotation
lymphoid <- c(32,9,24,50,51,10,4,19,22)
myeloid <- c(3,49,13,14,43,47,37,48,11)
basal <- c(30,18,34,39,28,38,52)
luminal <- c(46,20,16,2,29,26,27,31,41,36)

luminal <- paste0("C",luminal)
basal <- paste0("C",basal)
myeloid <- paste0("C",myeloid)
lymphoid <- paste0("C",lymphoid)
# unknown <- "C36"

sce$Groups <- mapvalues(as.character(sce$Cluster),
		       from=c(lymphoid, myeloid, basal, luminal, fibroblastsCluster, stromaCluster),
		       to=c(rep("Lymphoid",length(lymphoid)),
			    rep("Myeloid",length(myeloid)),
			    rep("Basal",length(basal)),
			    rep("Luminal",length(luminal)),
			    rep("Fibroblast",length(fibroblastsCluster)),
			    rep("Stroma",length(stromaCluster))))
			    
plotUMAP(sce, colour_by="MajorGroups", text_by="Cluster")
```

```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
pD <- data.frame(colData(sce))
pD.c <- pD[pD$Condition=="CTRL",]
pD.g1 <- pD[pD$Condition=="4.5dG",]
pD.g2 <- pD[pD$Condition=="9.5dG",]
pD.g3 <- pD[pD$Condition=="14.5dG",]

p.c <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point(color="grey80") +
    geom_point(data=pD.c,aes(color=MajorGroups)) +
    scale_color_brewer(palette="Dark2") +
    ggtitle("NP") +
    theme_void()
p.g1 <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point(color="grey80") +
    geom_point(data=pD.g1,aes(color=MajorGroups)) +
    scale_color_brewer(palette="Dark2") +
    ggtitle("4.5dG") +
    theme_void()
p.g2 <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point(color="grey80") +
    geom_point(data=pD.g2,aes(color=MajorGroups)) +
    scale_color_brewer(palette="Dark2") +
    ggtitle("9.5dG") +
    theme_void()
p.g3 <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point(color="grey80") +
    geom_point(data=pD.g3,aes(color=MajorGroups)) +
    scale_color_brewer(palette="Dark2") +
    ggtitle("14.5dG") +
    theme_void()
plot_grid(p.c,p.g1,p.g2,p.g3)
# ggsave("SplitPlot.pdf",width=10,height=10)


# For Walid
pD$Timepoint <- mapvalues(pD$Condition,
			  c("CTRL","4.5dG","9.5dG","14.5dG"),
			  c(0,4.5,9.5,14.5))
pD$Timepoint <- as.numeric(pD$Timepoint)
library(viridis)
ggplot(pD[sample(nrow(pD)),], aes(x=UMAP1, y=UMAP2, color=Timepoint)) +
    geom_point() +
    scale_color_viridis(begin=0,end=0.8,option="B")
# ggsave("UMAPColoredByTime.pdf")

ggplot(pD, aes(x=UMAP1, y=UMAP2,color=Cluster=="C3")) +
    geom_point() 

ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point() +
    facet_wrap(~Cluster)

```

# Cell Type mapping
- This is quite preliminary
```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
celltypes <- c(1:40)
celltypes <- paste0("C",celltypes)
#pDC because of Siglec-Hhttps://www.ncbi.nlm.nih.gov/pmc/articles/PMC3977341/
#MyUk1 is Cd209hi Dc
names(celltypes) <- c("Np", "Ec1", "Tc1", "Caf1", "Sc",
		      "Nk1", "Uk1", "Tam1", "Tm1", "Cd209DC",
		      "Lp", "Av", "Nk2", "Tm2", "Bc1",
		      "Mp2", "Tc2", "Mp1", "Bc2", "DCs",
		      "Bsl", "Fb1", "Hs", "Bc3", "Fb2",
		      "HsLpAv", "Tc3", "Tc4", "LpTm", "HsDbl",
		      "Ec2", "DcCcr7", "Fb3", "Ec3", "Fb4",
		      "BslBc", "pDC", "Fb5", "Tam1", "Fb6")
sce$CellTypes <- mapvalues(sce$Cluster, from=celltypes, to=names(celltypes))
sort(table(sce$CellTypes), decreasing=TRUE)
saveRDS(sce,file="../data/combined_Robjects/SCE_final.rds")
```
