---
title: "BRCA1 first look"
author: "Karsten Bach"
date: '`r Sys.Date()`'
output:
  html_notebook:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: united
    highlight: tango
---
***

# Load Data
```{r, message=FALSE}
library(scran)
library(scater)
library(dplyr)
library(knitr)
library(ggplot2)
library(Rtsne)
library(cowplot)
library(Matrix)
source("functions.R")

# Load Data
dataList <- readRDS("../data/Robjects/ExpressionList_QC.rds")
sfs <- read.csv("../data/Robjects/SizeFactors.csv")
m <- dataList[["counts"]]
pD <- dataList[["phenoData"]]
pD <- right_join(pD,sfs)
fD <- dataList[["featureData"]]
rm(dataList)
```

# Number of Cells
We sequenced a total of `r ncol(m)` cells.
```{r}
kable(t(as.matrix(table(pD$Condition))))
```

# Most of the variation in cell number is between biological replicates
```{r}
fp <- group_by(pD[!pD$AnimalHadTumor,], SampleID) %>%
    summarize(Number=n())
fp$Condition <- as.factor(substring(fp$SampleID,1,nchar(fp$SampleID)-1))
ggplot(fp, aes(x=Condition, y=Number)) +
    geom_point()
```

# Quality Control
```{r, fig.width=12, fig.height=12}
filt.gd1 <- min(pD$GenesDetected[pD$PassAll])
filt.gd2 <- max(pD$GenesDetected[pD$PassAll])
filt.lb1 <- min(pD$UmiSums[pD$PassAll])
filt.lb2 <- max(pD$UmiSums[pD$PassAll])
filt.mt <- max(pD$prcntMito[pD$PassAll])

# Quality Control
# Sequencing Depth and Genes detected
genesDetected <- ggplot(pD, aes(x=SampleID,y=GenesDetected,fill=Condition)) +
    geom_violin(draw_quantiles=0.5)+
    scale_y_log10() +
    ylab("Total number of genes detected") +
    xlab("") +
    geom_hline(yintercept=filt.gd1,lty="dashed",color="red") +
    geom_hline(yintercept=filt.gd2,lty="dashed",color="red") +
    scale_fill_brewer(palette="Dark2") +
    theme_bw() +
    theme(legend.position="none") +
    coord_flip()

LibrarySize <- ggplot(pD, aes(x=SampleID,y=UmiSums,fill=Condition)) +
    geom_violin(draw_quantiles=0.5)+
    scale_y_log10() +
    ylab("Total number of molecules") +
    xlab("") +
    geom_hline(yintercept=filt.lb1,lty="dashed",color="red") +
    geom_hline(yintercept=filt.lb2,lty="dashed",color="red") +
    scale_fill_brewer(palette="Dark2") +
    theme_bw() +
    theme(legend.position="none") +
    coord_flip()

cellViability <- ggplot(pD, aes(x=SampleID,y=prcntMito,fill=Condition)) +
    geom_violin(draw_quantiles=0.5)+
    ylab("Percentage of mitochondrial molecules") +
    xlab("") +
    geom_hline(yintercept=filt.mt,lty="dashed",color="red") +
    scale_fill_brewer(palette="Dark2") +
    theme_bw() +
    coord_flip()

sumry <- group_by(pD, SampleID) %>%
    summarize("# Before QC"=n(),
	      "Total molecules"=median(UmiSums),
	      "Genes Detected"=median(GenesDetected))
sumryAQC <- filter(pD, PassAll) %>%
    group_by(SampleID) %>%
    summarize("# After QC"=n())
sumry <- full_join(sumry,sumryAQC)
sumry <- sumry[,c(1,2,5,3,4)]
sumry <- group_by(pD, SampleID) %>%
    summarize("Number of cells"=n(),
	      "Total molecules"=median(UmiSums),
	      "Genes Detected"=median(GenesDetected))
kable(sumry,caption="Summary of QC parameters as median")


mytheme <- gridExtra::ttheme_default(
    core = list(fg_params=list(cex = 0.8)),
    colhead = list(fg_params=list(cex = 0.8)),
    rowhead = list(fg_params=list(cex = 0.8)))

p1 <- tableGrob(sumry,rows=NULL,theme=mytheme)
p2 <- plot_grid(genesDetected, LibrarySize, cellViability,nrow=1,rel_widths=c(1,1,1.3))
p3 <- plot_grid(p2,p1,nrow=2)

# Actually applying the filter
cells <- pD$barcode[pD$PassAll==TRUE & pD$sf>0.001]
m <- m[,cells]
pD <- pD[pD$barcode %in% cells,]
genes <- rowMeans(m)>0.01
m <- m[genes,]
```
