---
title: "Alveologenesis"
author: "Karsten Bach"
date: '`r Sys.Date()`'
output:
  html_notebook:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: united
    highlight: tango
    code_folding: hide
---
***

In this script I will put anything that is related to alveologenesis in the tumorigenesis and pregnancy dataset.
```{r, message=FALSE,warning=FALSE}
library(slingshot)
library(scran)
library(scater)
library(ggplot2)
library(cowplot)
library(Matrix)
library(umap)
library(dplyr)
library(viridis)
library(ggrastr)
source("../functions.R")
theme_set(theme_cowplot())

sce.full <- readRDS("../../data/Integrated//Robjects/SCE_combined_final.rds")

sce.full <- sce.full[,sce.full$MajorGroups=="Epithelial"]

sce <- sce.full[,sce.full$Experiment=="Tumorigenesis"]
rD <- rowData(readRDS("../../data/Tumorigenesis/Robjects/SCE.rds"))
rmgenes <- rownames(rD)[!rD$KeepForHvg]
rmgenes <- rownames(sce)[rownames(sce) %in% rmgenes]
outdr <- "../../data/figures/Figure3/"
```

# Overview

## Alveolar expression
```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
#fplot <- data.frame(colData(sce[,sce$CellTypesFinal=="Avd"]))

fplot <- data.frame()
genes <- c("Epcam","Krt8","Krt18","Csn2","Csn1s1","Glycam1","Wap","Lalba")
sce.av <- sce[,sce$CellTypesFinal=="Avd"]

for (gene in genes) {
    tmp <- data.frame("Expression"=logcounts(sce.av)[gene,],
		      "Gene"=gene)
    fplot <- rbind(fplot,tmp)
}

ggplot(fplot, aes(x=Gene,y=Expression)) +
    geom_jitter(size=.3,color="grey80") +
    stat_summary(fun = median, fun.min = median, fun.max = median,
                 geom = "crossbar", width = 0.5) +
    xlab("")

# Version 2
fplot <- data.frame()
genes <- c("Epcam","Krt8","Krt5","Krt17",
	   "Csn2","Csn1s1","Wap","Lalba",
	   "Elf5","Esr1","Cebpb","Sox10")
sce.av <- sce[,sce$CellTypesFinal=="Avd"]

for (gene in genes) {
    tmp <- data.frame("Expression"=logcounts(sce.av)[gene,],
		      "Gene"=gene)
    fplot <- rbind(fplot,tmp)
}

fplot$Category <- plyr::mapvalues(fplot$Gene,
				  c(c("Epcam","Krt8","Krt5","Krt17"),
				  c("Csn2","Csn1s1","Wap","Lalba"),
	 			  c("Elf5","Esr1","Cebpb","Sox10")),
				  c(rep("Epithelial",4),
				  rep("Milk Proteins",4),
				  rep("Luminal TFs",4)))

ggplot(fplot, aes(x=Gene,y=Expression)) +
    geom_jitter(size=.1,color="grey80") +
#    geom_violin(draw_quantiles=c(.5),scale="width") +
    stat_summary(fun = median, fun.min = median, fun.max = median,
		 geom = "crossbar", width = 0.5) +
    theme_pub() +
    theme(strip.background = element_rect(colour="white", fill="white")) +
    #           strip.text.x = element_text(size=12, face="bold") ,
    #           strip.text.y = element_text(size=12, face="bold"),
#               ,
    #           axis.line=element_line(size=1.5),
    #           axis.ticks=element_line(size=1.5)) +
    theme(axis.text.x=element_text(angle=45,face="italic",hjust=1)) +
    ylab("Expression") +
    xlab("")

ggsave(paste0(outdr,"Avd_Expression.pdf"))
```

```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
sce.av <- sce[,sce$CellTypesFinal %in% c("Lp","Avd")]
sce.av <- sce.av[,!sce.av$Condition %in% c("5","WTOld")]
sce.av <- sce.av[,sce.av$UMAP1 > -2.5] # removing a single cell that is sitting somewhere else
pD <- droplevels(data.frame(colData(sce.av)))

dpi <- 300

pltUMAP <- function(pD.sub,pD) {
    p <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
	geom_point(color="grey80",size=2) +
	geom_point(data=pD.sub, aes(fill=CellTypesFinal), size=2.1,pch=21,stroke=.1) +
	geom_density2d(data=pD.sub, color="black",lwd=.5)  +
	scale_fill_manual(values=levels(pD.sub$Colors)) +
	theme_void() +
	theme(legend.position="none")
    return(p)
}


# One with everything

p <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point(aes(fill=CellTypesFinal), size=2.1,pch=21,stroke=.1) +
    scale_fill_manual(values=levels(pD$Colors)) +
    theme_void() +
    theme(legend.position="none")

ggsave(paste0(outdr,"UMAP_LP_All.png"),p,dpi=dpi, width=3, height=3)


ggsave(paste0(outdr,"UMAP_LP_Stage_1_Dens.png"),pltUMAP(pD[pD$Condition=="1",],pD),dpi=dpi, width=3, height=3)
ggsave(paste0(outdr,"UMAP_LP_Stage_2_Dens.png"),pltUMAP(pD[pD$Condition=="2",],pD),dpi=dpi, width=3, height=3)
ggsave(paste0(outdr,"UMAP_LP_Stage_3_Dens.png"),pltUMAP(pD[pD$Condition=="3",],pD),dpi=dpi, width=3, height=3)
ggsave(paste0(outdr,"UMAP_LP_Stage_4_Dens.png"),pltUMAP(pD[pD$Condition=="4",],pD),dpi=dpi, width=3, height=3)

pltGEXUMAP <- function(pD,gene) {
    mx <- quantile(pD$Expr,.99)
    pD$Expr[pD$Expr>mx] <- mx
    p <- ggplot(pD, aes(x=UMAP1, y=UMAP2, fill=gene)) +
	geom_point(size=2,pch=21,stroke=.1) +
	theme_void() +
	scale_fill_viridis(option="C") +
	theme(legend.position="none")
    return(p)
}


genes <- c("Csn2","Aldh1a3","Wap","Lalba","Cebpb","Elf5","Cebpb")
for (gene in genes) {
    pD$Expr <- logcounts(sce.av)[gene,]
    ggsave(paste0(outdr,gene,"_LP_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi,width=3,heigh=3)
}

# Some GEX with schex
library(schex)
sce.av <- make_hexbin(sce.av, nbins = 50, 
		   dimension_reduction = "UMAP", use_dims=c(1,2))
pltGEX <- function(sce, gene) {
    plot_hexbin_gene(sce, gene=gene, type="logcounts",
		     action="mean") +
	theme_void() +
	theme(legend.position="none") +
	scale_fill_viridis(option="C") +
	ggtitle("")
}

for (gene in genes) {
    pD$Expr <- logcounts(sce.av)[gene,]
    ggsave(paste0(outdr,gene,"_LP_UMAP_Schex.png"),pltGEX(sce.av,gene),dpi=dpi,width=3,heigh=3)
}

```

## UMAPS
```{r, fig.width=7, fig.height=7, warning=FALSE, message=FALSE}
pD <- data.frame(colData(sce))
pD <- droplevels(pD[pD$Condition!="WTOld",])
sumry <- group_by(pD, ptimeBin, CellTypesFinal) %>%
    summarize(n=n()) %>%
    mutate(frac=n/sum(n)) %>%
    ungroup()

comb <- table(sumry$CellTypesFinal,sumry$ptimeBin) 
missing.comb <- which(comb==0, arr.ind=TRUE)
if (nrow(missing.comb)>0) {
    add.missing <- data.frame("CellTypesFinal"=rownames(missing.comb),
		      "ptimeBin"=colnames(comb)[missing.comb[,"col"]],
		      "frac"=0,
		      "n"=0)
    sumry <- rbind(sumry,add.missing)
}
sumry$ptimeBin <- as.numeric(sumry$ptimeBin)

sumry$Colors <- plyr::mapvalues(as.character(sumry$CellTypesFinal),
				as.character(unique(pD$CellTypesFinal)),
				as.character(unique(pD$Colors)))

# combi <- unique(paste0(substr(pD$MajorGroups,1,3),"-",as.character(pD$CellTypesFinal)))
# names(combi) <- unlist(lapply(strsplit(combi,"-"),function(x) x[[2]]))
# sumry$CellTypesFinal <- plyr::mapvalues(as.character(sumry$CellTypesFinal),
#                                    as.character(names(combi)),
#                                    as.character(combi))

sumry <- arrange(sumry, ptimeBin, CellTypesFinal) %>%
    group_by(ptimeBin) %>%
    mutate(cumfrac=cumsum(frac)) %>%
    ungroup()

barplt <- ggplot(sumry, aes(x=factor(ptimeBin,levels=c(5,4,3,2,1)), y=frac, fill=CellTypesFinal)) +
    geom_bar(stat="identity",color="black") +
    scale_fill_manual(values=unique(sumry$Colors)) +
    xlab("Tumortime Bin") +
    ylab("Fraction of Cells") +
    coord_flip()
ggsave(paste0(outdr,"Barplot_CellTypes.pdf"),barplt)
```

```{r, fig.width=10, fig.height=4, warning=FALSE, message=FALSE}
pD <- data.frame(colData(sce.full))
pD$CellTypesFinal <- pD$CellTypesFinal <- droplevels(pD$CellTypesFinal)
pD$Colors <- droplevels(pD$Colors)

dpi <- 900
pltUMAP <- function(pD.sub,pD) {
    p <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
	geom_point_rast(color="grey80",size=1,dpi=dpi) +
	geom_point_rast(data=pD.sub, aes(fill=CellTypesFinal), size=1,dpi=dpi,pch=21,stroke=.1) +
	scale_fill_manual(values=levels(pD.sub$Colors)) +
	theme_void() +
	theme(legend.position="none")
    return(p)
}
pltUMAPFull <- function(pD.sub,pD) {
    p <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
	geom_point_rast(data=pD.sub, aes(fill=CellTypesFinal), size=1,dpi=dpi,pch=21,stroke=.1) +
	scale_fill_manual(values=levels(pD.sub$Colors)) +
	theme_void() +
	theme(legend.position="none")
    return(p)
}


set.seed(42)
# This includes the pregnancy in the background
pD1 <- pD[pD$Condition==1,]
#pD1 <- pD1[sample(nrow(pD1),2534),]

pD2 <- pD[pD$Condition==2,]
#pD2 <- pD2[sample(nrow(pD2),2534),]

pD3 <- pD[pD$Condition==3,]
#pD3 <- pD3[sample(nrow(pD3),2534),]

pD4 <- pD[pD$Condition==4,]
pD5 <- pD[pD$Condition==5,]
#pD4 <- pD4[sample(nrow(pD4),2534),]
pDNP <- pD[pD$Condition=="WTYoung",]
pD4dG <- pD[pD$Condition=="4.5dG",]
pD9dG <- pD[pD$Condition=="9.5dG",]
pD14dG <- pD[pD$Condition=="14.5dG",]

# ggsave(paste0(outdr,"UMAP_All.png"),pltUMAPFull(pD,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_Bin_1.png"),pltUMAP(pD1,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_Bin_2.png"),pltUMAP(pD2,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_Bin_3.png"),pltUMAP(pD3,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_Bin_4.png"),pltUMAP(pD4,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_Bin_5.png"),pltUMAP(pD5,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_NP.png"),pltUMAP(pDNP,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_4dG.png"),pltUMAP(pD4dG,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_9dG.png"),pltUMAP(pD9dG,pD),dpi=dpi)
# ggsave(paste0(outdr,"UMAP_14dG.png"),pltUMAP(pD14dG,pD),dpi=dpi)



# Some GEX
pltGEXUMAP <- function(pD,gene) {
    mx <- quantile(pD$Expr,.99)
    pD$Expr[pD$Expr>mx] <- mx
    p <- ggplot(pD, aes(x=UMAP1, y=UMAP2, fill=gene)) +
	geom_point_rast(size=1,dpi=dpi,pch=21,stroke=.1) +
	theme_void() +
	scale_fill_viridis(option="C") +
	theme(legend.position="none")
    return(p)
}
# pD$Expr <- logcounts(sce.full)["Krt5",]
# ggsave(paste0(outdr,"Krt5_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi)
# pD$Expr <- logcounts(sce.full)["Krt8",]
# ggsave(paste0(outdr,"Krt8_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi)
# pD$Expr <- logcounts(sce.full)["Aldh1a3",]
# ggsave(paste0(outdr,"Aldh1a3_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi)
# pD$Expr <- logcounts(sce.full)["Csn2",]
# ggsave(paste0(outdr,"Csn2_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi)
# pD$Expr <- logcounts(sce.full)["Cited1",]
# ggsave(paste0(outdr,"Cited1_UMAP.png"),pltGEXUMAP(pD,pD$Expr),dpi=dpi)

# Some GEX with schex

library(schex)
sce.preg <- make_hexbin(sce.full[,sce.full$Experiment=="Pregnancy"], nbins = 50, 
		   dimension_reduction = "UMAP", use_dims=c(1,2))

pltGEX <- function(sce, gene) {
    plot_hexbin_gene(sce, gene=gene, type="logcounts",
		     action="mean") +
	theme_void() +
	theme(legend.position="none") +
	scale_fill_viridis(option="C") +
	ggtitle("")
}


ggsave(paste0(outdr,"Csn2_UMAP_Bin.png"),pltGEX(sce.preg,"Csn2"))
ggsave(paste0(outdr,"Krt5_UMAP_Bin.png"),pltGEX(sce.preg,"Krt5"))
ggsave(paste0(outdr,"Krt8_UMAP_Bin.png"),pltGEX(sce.preg,"Krt8"))
ggsave(paste0(outdr,"Aldh1a3_UMAP_Bin.png"),pltGEX(sce.preg,"Aldh1a3"))
ggsave(paste0(outdr,"Cited1_UMAP_Bin.png"),pltGEX(sce.preg,"Cited1"))
ggsave(paste0(outdr,"Rankl_UMAP_Bin.png"),pltGEX(sce.preg,"Tnfsf11"))
ggsave(paste0(outdr,"Calca_UMAP_Bin.png"),pltGEX(sce.preg,"Calca"))
ggsave(paste0(outdr,"Ki67_UMAP_Bin.png"),pltGEX(sce.preg,"Mki67"))

ggsave(paste0(outdr,"Adamts18_UMAP_Bin.png"),pltGEX(sce.preg,"Adamts18"))
ggsave(paste0(outdr,"Col4a1_UMAP_Bin.png"),pltGEX(sce.preg,"Col4a1"))
ggsave(paste0(outdr,"Acta2_UMAP_Bin.png"),pltGEX(sce.preg,"Acta2"))

p <- plotExpression(sce.full[,sce.full$CellTypesFinal %in% c("Lp","Avd")],x="Experiment","Mki67") 

p +
    xlab("") +
    ylab("Ki67") +
    theme(text=element_text(size=16,face="bold"),
	  axis.text=element_text(size=14,face="bold"))

library(schex)
# Only Tumor
sce.t <- sce.full[,sce.full$Condition %in% c(1,2,3,4,5)]
colnames(sce.t) <- sce.t$barcode
dwnsmp <- data.frame(colData(sce.t)) %>%
    group_by(Condition) %>%
    sample_n(2534) %>%
    .$barcode
sce.t <- sce.t[,dwnsmp]
sce.t <- make_hexbin(sce.t, nbins = 100, 
		   dimension_reduction = "UMAP", use_dims=c(1,2))

# Only Pregnancy
sce.p <- sce.full[,sce.full$Condition %in% c("WTYoung","4.5dG","9.5dG","14.5dG")]
colnames(sce.p) <- sce.p$barcode
dwnsmp <- data.frame(colData(sce.p)) %>%
    group_by(Condition) %>%
    sample_n(6597) %>%
    .$barcode
sce.p <- sce.p[,dwnsmp]
sce.p <- make_hexbin(sce.p, nbins = 100, 
		   dimension_reduction = "UMAP", use_dims=c(1,2))

# No WTOld to compare the two (doesn't make much of a diff)
sce.sub <- sce.full[,!sce.full$Condition %in% "WTOld"]
colnames(sce.sub) <- sce.sub$barcode
dwnsmp <- data.frame(colData(sce.sub)) %>%
    group_by(Experiment) %>%
    sample_n(26979) %>%
    .$barcode

sce.sub <- sce.sub[,dwnsmp]
sce.sub <- make_hexbin(sce.sub, nbins = 100, 
		   dimension_reduction = "UMAP", use_dims=c(1,2))


library(RColorBrewer)
cols.t <- brewer.pal(n=6,"PuRd")
hx.t <- plot_hexbin_meta(sce.t, col="Condition", action="majority") +
    scale_fill_manual(values=cols.t[2:6]) +
    theme_void() +
    theme(text=element_text(size=14)) +
    theme(legend.position="left",
	  legend.title=element_blank()) +
    ggtitle("")

ggsave(paste0(outdr,"UMAP_Tumor_Epithelium_Bins_SS.pdf"),hx.t)

cols.p <- brewer.pal(n=5,"GnBu")
hx.p <- plot_hexbin_meta(sce.p, col="Condition", action="majority") +
    scale_fill_manual(values=cols.p[2:5]) +
    theme_void() +
    theme(text=element_text(size=14)) +
    theme(legend.position="left",
	  legend.title=element_blank()) +
    ggtitle("")

ggsave(paste0(outdr,"UMAP_Pregnancy_Epithelium_Bins_SS.pdf"),hx.p)
plot_grid(hx.t,hx.p)

hx.c <- plot_hexbin_meta(sce.sub, col="Experiment", action="prop") +
    theme_void() +
    ggtitle("") +
    theme(text=element_text(size=14),
	  legend.title=element_blank()) +
    scale_fill_gradient2(low=cols.t[5],high=cols.p[5],mid="white",midpoint=0.5) 

ggsave(paste0(outdr,"UMAP_TumorVsPregnancy_Epithelium_Bins_SS.pdf"),hx.c)
```


## Plotting various genes


## Markers for the various populations
```{r, fig.width=11, fig.height=3, warning=FALSE, message=FALSE}
# Plotting UMAP 
pD <- droplevels(data.frame(colData(sce.full)))

p <- ggplot(pD, aes(x=UMAP1, y=UMAP2)) +
    geom_point_rast(aes(fill=CellTypesFinal), size=1.8,dpi=900,pch=21,stroke=.2) +
    scale_fill_manual(values=levels(pD$Colors)) +
    theme_void() +
    theme(legend.position="none")
ggsave(paste0(outdr,"UMAP_Epithelium.png"),p)


markers <- findMarkers(sce.full,factor(sce.full$CellTypesFinal),
		       pval.type="all",
		       direction="up",
		       block=sce.full$Batch,
		       subset.row=!rownames(sce.full) %in% rmgenes)
genes <- lapply(markers,function(x) rownames(x)[1:10])
genes <- do.call(c,genes)
genes <- unique(genes)
require(reshape2)
bubblePlot(logcounts(sce.full), genes, factor(sce.full$CellTypesFinal) ,angled=TRUE) %+% coord_flip() +
    scale_color_gradient2(low="white",high="red")
ggsave(paste0(outdr,"GEX_Heatmap_horizontal.pdf"),width=7,height=3)
p <- bubblePlot(logcounts(sce.full), genes, factor(sce.full$CellTypesFinal) ,angled=TRUE)
ggsave(paste0(outdr,"GEX_Heatmap_vertical.pdf"),p,width=3,height=7)

genes <- c("Krt5","Krt8","Krt18","Acta2","Elf5","Csn2","Csn1s1","Glycam1","Wap",
	   "Esr1","Cited1","Pgr","Ly6a","Aldh1a3","Kit","Cd14","Lalba","Prlr",
	   "Col4a1","Epcam","Asz1","Skap1","Oas2","Lgals3bp",
	   "Cxcl14","Sfn","Socs3","Egr2","Gas1","Actg2")
sce.full$CellTypesFinal <- renameForPlot(sce.full$CellTypesFinal)
bubblePlot(logcounts(sce.full), genes, sce.full$CellTypesFinal ,angled=TRUE) %+% coord_flip() +
    scale_color_gradient2(low="white",high=hi) +
    theme(axis.text=element_text(size=10))
ggsave(paste0(outdr,"GEX_selected_Heatmap_horizontal.pdf"),width=6,height=3)
bubblePlot(logcounts(sce.full), genes, sce.full$CellTypesFinal ,angled=TRUE) +
    scale_color_gradient2(low="white",high=hi) +
    theme(axis.text=element_text(size=10))
ggsave(paste0(outdr,"GEX_selected_Heatmap_vertical.pdf"),height=6,width=3)
```
